import { Platform, StyleSheet } from "react-native";
export const C = {
  navy: "#101E30",
  blue: "#265DE8",
  ink: "#142337",
  muted: "#778395",
  line: "#E5EAF1",
  bg: "#F5F7FA",
  white: "#FFFFFF",
  green: "#2E9472",
};
export const s = StyleSheet.create({
  app: { flex: 1, backgroundColor: C.bg },
  layout: { flex: 1, flexDirection: "row" },
  main: { flex: 1, minWidth: 0 },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  sidebar: { width: 256, backgroundColor: C.navy, padding: 20, paddingTop: 28 },
  brand: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    marginBottom: 39,
  },
  brandMark: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: "#294B75",
    alignItems: "center",
    justifyContent: "center",
  },
  brandText: {
    color: "white",
    fontSize: 23,
    fontWeight: "700",
    letterSpacing: -0.6,
  },
  workspaceLabel: {
    color: "#73869F",
    fontSize: 10,
    fontWeight: "600",
    letterSpacing: 1.4,
    marginBottom: 12,
  },
  domainCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 12,
    backgroundColor: "#1A2C43",
    borderRadius: 8,
  },
  dot: { width: 6, height: 6, borderRadius: 4, backgroundColor: "#53BC97" },
  domainName: { color: "#DCE5F0", fontSize: 12, flex: 1 },
  composeButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: C.blue,
    paddingVertical: 13,
    paddingHorizontal: 13,
    borderRadius: 8,
    marginTop: 23,
    marginBottom: 31,
  },
  composeButtonText: { color: "white", fontSize: 12, fontWeight: "600" },
  navLabel: {
    fontSize: 10,
    letterSpacing: 1.3,
    color: "#667C99",
    marginBottom: 12,
    paddingLeft: 10,
  },
  navItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 12,
    paddingVertical: 13,
    borderRadius: 7,
    marginBottom: 4,
  },
  navActive: { backgroundColor: "#203757" },
  navText: { fontSize: 12, color: "#9AAFC9", flex: 1 },
  navCount: {
    fontSize: 10,
    color: "#8FA3BD",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  sidebarFoot: {
    padding: 12,
    borderTopColor: "#28374C",
    borderTopWidth: 1,
    paddingTop: 20,
  },
  syncTime: { fontSize: 10, color: "#637994", marginTop: 7, marginLeft: 14 },
  profile: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingTop: 19,
    marginTop: 10,
    borderTopWidth: 1,
    borderColor: "#28374C",
  },
  avatarSmall: {
    width: 34,
    height: 34,
    borderRadius: 18,
    backgroundColor: "#2A405E",
    alignItems: "center",
    justifyContent: "center",
  },
  topbar: {
    height: 70,
    paddingHorizontal: 26,
    borderBottomWidth: 1,
    borderColor: C.line,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "white",
  },
  breadcrumb: { fontSize: 12, color: C.muted },
  breadcrumbCurrent: { fontSize: 12, color: C.ink, fontWeight: "500" },
  heading: {
    paddingHorizontal: 38,
    paddingTop: 35,
    paddingBottom: 29,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  title: { fontSize: 29, fontWeight: "600", letterSpacing: -1, color: C.ink },
  subtitle: { fontSize: 12, color: C.muted, marginTop: 9 },
  today: { color: C.muted, fontSize: 11, textTransform: "capitalize" },
  unreadBadge: {
    backgroundColor: "#E6EDFE",
    borderRadius: 5,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  unreadBadgeText: { color: C.blue, fontSize: 10, fontWeight: "600" },
  mailbox: {
    flex: 1,
    marginHorizontal: 36,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 12,
    backgroundColor: "white",
    overflow: "hidden",
  },
  listToolbar: {
    height: 65,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderBottomWidth: 1,
    borderColor: C.line,
  },
  search: { flexDirection: "row", gap: 10, alignItems: "center", flex: 1 },
  searchInput: {
    flex: 1,
    fontSize: 12,
    color: C.ink,
    paddingVertical: 10,
    minWidth: 0,
  },
  listCount: { fontSize: 10, color: "#9AA4B2" },
  mailRow: {
    flexDirection: "row",
    gap: 14,
    paddingHorizontal: 23,
    paddingVertical: 22,
    borderBottomWidth: 1,
    borderColor: "#EEF1F6",
    alignItems: "center",
  },
  mailRowUnread: { backgroundColor: "#FAFCFF" },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#EBEFFB",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { fontSize: 13, fontWeight: "600", color: "#65759A" },
  rowSender: { fontSize: 13, color: C.ink, fontWeight: "500" },
  rowSubject: { fontSize: 12, color: "#536177", marginTop: 6 },
  rowDate: { fontSize: 10, color: "#8A97AA" },
  preview: { fontSize: 11, color: "#8C98AA", marginTop: 5, lineHeight: 18 },
  unreadDot: { width: 6, height: 6, borderRadius: 4, backgroundColor: C.blue },
  endList: { textAlign: "center", fontSize: 11, color: "#AFB7C3", padding: 25 },
  bottomNote: {
    paddingHorizontal: 36,
    paddingVertical: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  bottomNoteText: { fontSize: 10, color: "#8A96A7" },
  empty: { alignItems: "center", paddingVertical: 90, paddingHorizontal: 25 },
  emptyIcon: {
    width: 78,
    height: 78,
    borderRadius: 24,
    backgroundColor: "#EDF2FF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 23,
  },
  emptyTitle: {
    fontSize: 19,
    color: C.ink,
    fontWeight: "500",
    textAlign: "center",
  },
  emptyText: {
    fontSize: 12,
    color: C.muted,
    lineHeight: 21,
    textAlign: "center",
    maxWidth: 340,
    marginTop: 10,
  },
  button: {
    paddingVertical: 12,
    paddingHorizontal: 17,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: "white",
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  primary: { backgroundColor: C.blue, borderColor: C.blue },
  buttonText: { fontSize: 12, color: C.ink, fontWeight: "600" },
  iconButton: { padding: 10, alignItems: "center", justifyContent: "center" },
  input: {
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 8,
    paddingHorizontal: 13,
    paddingVertical: 12,
    fontSize: 14,
    color: C.ink,
    backgroundColor: "white",
  },
  label: { fontSize: 11, color: "#637084", fontWeight: "600" },
  link: { color: C.blue, fontSize: 12 },
  meta: { fontSize: 11, color: C.muted, lineHeight: 18 },
  banner: {
    marginHorizontal: 20,
    marginTop: 12,
    padding: 12,
    borderRadius: 7,
    backgroundColor: "#EAF6EF",
    flexDirection: "row",
    gap: 8,
  },
  errorText: { color: "#B64133", fontSize: 12, lineHeight: 20 },
  readerToolbar: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    flexDirection: "row",
    borderBottomWidth: 1,
    borderColor: C.line,
    backgroundColor: "white",
  },
  reader: { padding: 36 },
  readerCard: {
    padding: 26,
    borderRadius: 12,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: C.line,
  },
  subject: { fontSize: 26, fontWeight: "600", color: C.ink, marginBottom: 25 },
  senderLine: {
    flexDirection: "row",
    gap: 14,
    alignItems: "center",
    paddingBottom: 23,
    borderBottomWidth: 1,
    borderColor: C.line,
  },
  senderName: { fontSize: 13, fontWeight: "600", color: C.ink },
  messageBody: {
    fontSize: 15,
    lineHeight: 26,
    color: "#34465E",
    paddingVertical: 28,
  },
  attachments: { gap: 10, marginBottom: 24 },
  attachment: {
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 8,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#FAFBFD",
  },
  attachmentName: { fontSize: 12, color: C.ink },
  readerActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    paddingTop: 15,
  },
  busyOverlay: {
    position: "absolute",
    right: 20,
    top: 76,
    padding: 12,
    backgroundColor: "white",
    borderRadius: 30,
  },
  login: {
    flex: 1,
    backgroundColor: C.navy,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  loginCard: {
    width: "100%",
    maxWidth: 440,
    backgroundColor: "white",
    padding: 34,
    borderRadius: 20,
    gap: 20,
  },
  logo: {
    backgroundColor: C.blue,
    width: 54,
    height: 54,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  loginTitle: {
    fontSize: 30,
    lineHeight: 36,
    fontWeight: "600",
    letterSpacing: -1,
    color: C.ink,
  },
  loginText: { fontSize: 13, lineHeight: 22, color: C.muted },
  loginFoot: { textAlign: "center", fontSize: 10, color: "#8B97A7" },
  modalOverlay: {
    flex: 1,
    backgroundColor: "#101E3088",
    justifyContent: "center",
    alignItems: "center",
    padding: Platform.OS === "web" ? 24 : 0,
  },
  composer: {
    width: "100%",
    maxWidth: 760,
    maxHeight: "95%",
    backgroundColor: "white",
    borderRadius: 14,
    overflow: "hidden",
    flex: 1,
  },
  modalHeader: {
    paddingHorizontal: 24,
    paddingVertical: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderColor: C.line,
  },
  modalTitle: { fontSize: 19, color: C.ink, fontWeight: "600" },
  composeFields: { padding: 24, gap: 17 },
  bodyInput: {
    minHeight: 230,
    fontSize: 15,
    lineHeight: 25,
    color: C.ink,
    paddingVertical: 14,
  },
  composeFooter: {
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderColor: C.line,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  chip: {
    backgroundColor: "#EEF3FE",
    borderRadius: 20,
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  chipText: { fontSize: 11, color: C.blue },
  settingsTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: C.ink,
    marginTop: 8,
  },
  domainStatus: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 15,
    borderRadius: 8,
    backgroundColor: "#F0F8F4",
  },
  identityEditor: {
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 9,
    padding: 16,
    gap: 12,
  },
});
